### ISSUE TITLE
Completion does not propose method refs

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#169]
Given:

```ceylon
"".split("".eq);
```

I expect autocompletion to propose both `equals(Object that)` and the method reference `equals`, like in Eclipse. But in IntelliJ it only proposes the completion with filled-in arguments. (Could be an issue with proposal equality, perhaps?)

**Comment by bjansen** [comment]
Actually the function reference doesn't appear because `String`, `Integer` etc. are loaded from their `.class` file, and all their methods are overloaded:

```java
public boolean equals(@Name("that") Object that) { }
public static boolean equals(java.lang.String value, Object that) { }
```

This results in my model loader detecting those overloads, and the completion manager refusing to show refs for overloaded methods.

You can see that the proposal is shown for Ceylon declarations like `ArrayList()`.

`JDTMethod` does additional checks to determine if two functions are overloads, so I think I'll do something similar:

```
            if(inheritedMethod.isPrivate()
                    || inheritedMethod.isStatic()
                    || inheritedMethod.isConstructor()
                    || inheritedMethod.isBridge()
                    || inheritedMethod.isSynthetic()
                    || !Arrays.equals(inheritedMethod.constantPoolName(), method.selector))
                continue;
```

**Comment by gavinking** [comment]
@bjansen Then that's a model loader bug. The static overload of `equals()` is annotated `@Ignore`.
