### ISSUE TITLE
Extract Variable buttons disabled until I edit the suggested name

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#173]
The Preview and Refactor buttons are initially disabled. They shouldn't be.

**Comment by bjansen** [comment]
Well they are disabled because until you change the name there's nothing to preview/apply because it has already been set as the default name by the refactoring.

But now that I fixed the inplace renaming, extract variable will show the red rectangle instead of the popup, so this issue has become obsolete.
