### ISSUE TITLE
popup message when click-navigating

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#191]
In the Java editor, holding ⌘ and clicking on a reference shows me the full signature of the referenced declaration in a little popup. In the Ceylon editor it just shows me the name.

**Comment by gavinking** [comment]
I have done a little bit of work on this, but then I gave up because I simply can't find the code that renders the labels of form:

> interface "ceylon.language::Enumerable" [Enumerable.ceylon]

I want to fix the following things about that:

- I want to remove the stupid double quotes
- I want to fix the keyword at the start, which is sometimes wrong ("attribute" or "getter" instead of `value`, etc).
- I need to escape `<` and `&`
- I would like to be able to do syntax highlighting on it (it's already HTML, after all)

**Comment by bjansen** [comment]
So, it turns out `org.intellij.plugins.ceylon.ide.doc.CeylonDocProvider#getQuickNavigateInfo` is called first, but since it used to return `null`, `ElementDescriptionProvider`s were called to generate the content. I implemented `getQuickNavigateInfo` and we now have better control over what's displayed (including colors!).

**Comment by gavinking** [comment]
Excellent! thanks :)

**Comment by bjansen** [comment]
I think this one has been completely fixed now, right?

**Comment by gavinking** [comment]
I guess.
