### ISSUE TITLE
occurrence highlighting and references to objects

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#236]
The purple occurrence highlighting doesn't seem to work for references to `object` declarations like `true` or `larger` or `process`, nor for their members.

**Comment by gavinking** [comment]
Nor does it work for the LHS of a shortcut refinement.

**Comment by bjansen** [comment]
Part of the problem is that my algorithm that determines if a declaration is visible "outside the current file" is broken. This scope is what's used by IntelliJ to use either inplace or dialog-based renaming.

If I decide that the scope is "file only", occurrences won't be highlighted if the declaration is located in an other file. On the other hand, if I decide that the scope is "project" or larger, renames will always be dialog-based.

Do we already have a piece of code that can determine if a name is visible from other files? (i.e. toplevel declarations and their parameters, shared members and maybe more).

**Comment by gavinking** [comment]
@bjansen Well "file only" isn't really a defined scope in Ceylon. The only things that are "file only" are things that are nested inside something else and not `shared`.

**Comment by gavinking** [comment]
i.e. what's wrong with `!dec.toplevel && !dec.shared`?

Perhaps you need a special case for parameters: i.e. `dec.parameter && (dec.initializerParamer.declaration.toplevel || dec.initializerParamer.declaration.shared)` since parameters inherit their visibility from the thing they parameterize.

**Comment by bjansen** [comment]
Yeah, that looks like what I'm looking for, I was using `!dec.scope is Package` instead, I totally forgot we had `.toplevel`. I'll give it a try.

**Comment by gavinking** [comment]
Thanks, better now.
