### ISSUE TITLE
renaming value with setter

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#275]
I tried to rename `integer` in this code, and the setter did not get renamed:

```ceylon
void foo() {
	print(Foo().integer = 12);
}

class Foo() {
	shared Integer integer => 0;
	assign integer {
		print(integer);
	}
}
```

**Comment by bjansen** [comment]
That's because `integer` in L7 references L6, but `integer` in L2 references L5, so IntelliJ thinks they are two different declarations, and only renames one:

```ceylon
1 void foo() {
2    print(Foo().integer = 12);
3 }

4 class Foo() {
5    shared Integer integer => 0;
6    assign integer {
7        print(integer);
8    }
9 }
```

Would it make more sense that both L2, L6 and L5 reference the same declaration in L5? In the same way shortcut refinements reference the refined declaration.

**Comment by gavinking** [comment]
No, I'm definitely not going to change the type checker :)

Look at how this works in Eclipse's rename refactoring.

**Comment by bjansen** [comment]
No, I mean when we ctrl-click on L6 it would send you to L5.

**Comment by gavinking** [comment]
That's fine by me. But look, I use a subclass of FindReferencesVisitor in Eclipse. I don't try to shoehorn everything into one class.
