### ISSUE TITLE
Non-final methods in CeylonParser

### ISSUE THREAD

**Issue by mmazi** [ceylon/ceylon-ide-intellij#3]
The approach we're currently using for parsing in the plugin is to extend CeylonParser and override its methods. The problem is that ANTLR creates all methods as final. The current workaround is to have a copy of CeylonParser.java in the plugin code with final keywords removed.

(The only reason I can think of for ANTLR creating final methods is speed (I imagine static linking can be used for final methods which could improve performance), though a quick Google search seems to indicate that final methods have dubious performance gains.)

I see several ways how to go about resolving this:

1. Copying CeylonParser.java into the plugin, as we do now.
2. Including an ant task in ceylon-spec that removes the final keywords from the methods in CeylonParser.java, after this file has been created by ANTLR.
3. As an alternative to 2., using some sort of bytecode manipulation to change CeylonParser.class, after it has been compiled, if this is even possible. (I see no benefits of this compared to 2.)
4. Using some (other) form of interceptors (or AOP) to do what we currently do in the extended CeylonParser (though this may be impossible with final methods?).
5. Using a modified version of ANTLR that produces non-final methods (Ceylon is probably tied to an od ANTLR version anyway).

2. and 5. seem to me the most viable options. They would both negate any performance benefits to using final methods though (even in non-Intellij environments), if these exist.

Or we could stick with 1. IIUC, we'll need to create a new version of the plugin for every new version of Ceylon anyway. (I'd rename the CeylonParser class in the plugin to something else though to avoid conflicts.)

**Comment by davidfestal** [comment]
I implemented solution 2 in e620629f4cd14973c1eb39eb4d5420fe48d98f22
I didn't change the name, because this brings problems in other places in the code that uses CeylonParser.
I also created a program that automatically changes TokenTypes accordingly.

**Comment by davidfestal** [comment]
Well, no, in fact commit e620629f4cd14973c1eb39eb4d5420fe48d98f22 implemented solution 1 *without* renaming the class (because the constructor of the `ParseError` class is awaiting a `CeylonParser` argument).
But having the a class with the same name a 2 places (in the typechecker archive *and* in the /classes plugin sub-direcrory) has brought LinkageError exceptions at runtime (when trying to load Ceylon runtime classes in a parent class loader). Though it was during experiments, it is an example of the problems we might encounter if we don't rename the modified `CeylonParser` class.
This is surely *not* a good solution to have 2 different versions of a class accessible from a single location.
