### ISSUE TITLE
errors after project Rebuild

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#363]
I rebuilt the project and got a bunch of these attached to the tree:

> the 'UnitDependencyVisitor' caused an exception visiting a 'QualifiedMemberExpression' node: '"com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation"' at 'com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:749)'

**Comment by davidfestal** [comment]
Please can you provide a more complete stack trace ?

**Comment by gavinking** [comment]
I don't have anything else, I'm sorry.

**Comment by davidfestal** [comment]
The commit  @417e0ec will help catching this error correctly and retrieving the whole call stack, instead of attaching it to the AST. This will help to know where to add the correct indexing strategy.

**Comment by davidfestal** [comment]
@gavinking : I couldn't reproduce this until now, and without a stacktrace I don't have enough information to identify the root cause.

However I made so that this type of exceptions will not be caught by the typechecking visitors anymore: when this happens again, we should now have a full stacktrace to further analyze the problem.

**Comment by gavinking** [comment]
I get it basically every second time I try to Make the IDE project after a change.

**Comment by gavinking** [comment]
Oh, wait, no, I'm thinking of #379. OK, we can close this for now, since #379 is far more urgent.
