### ISSUE TITLE
Build > Rebuild Project followed by Run results in unnecessary Make

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#411]
If I do Rebuild Project and then immediately run the project, an additional, unnecessary Make happens.

**Comment by bjansen** [comment]
It only happens in IJ modules that are dependencies of other modules, like ceylon-ide-intellij which depends on ceylon-ide-common in our project. To fix https://github.com/ceylon/ceylon-ide-eclipse/issues/1070, @davidfestal checked for folder deletions in the output repository in order to force a full build ("if `modules` is incomplete/was deleted, we should rebuild the project").

The problem here is that Rebuild Project deletes `ceylon-ide-common/modules`, which triggers a folder removal event, which is processed by the model manager, and will cause a full build the next time Make is invoked.

As a temporary fix, I'll comment the code that checks for folder removals in output repositories. It won't break Eclipse because it's not currently using the new build ported to ceylon-ide-common. 

A correct fix will be implemented in https://github.com/ceylon/ceylon-ide-common/issues/78
