### ISSUE TITLE
Android: newly Ceylon-converted project does not allow deleting Java file

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#434]
When I convert my new AS project to Ceylon, I have `MainActivity.java` and `MainActivity.ceylon`. I understand why we're not deleting the java files during the conversion, but when I manually delete it, AS will tell me it's still referenced, leading me to think something went wrong. It's not entirely true, because I have a `MainActivity.ceylon`. Perhaps this is a consequence of #350?

In any case it's wrong to have two classes with the same name, but there are no errors shown, so we should find a better way to deal with this.

**Comment by bjansen** [comment]
It's referenced in the manifest, so I guess even when #350 is fixed, IntelliJ will be able to navigate from the XML file to either of the two versions of the activity, so I think it will always say that the class is referenced...

We can either automatically delete the original Java version, or perhaps give a different name to the Ceylon version?

**Comment by FroMage** [comment]
Well, how is this file generated? If we're converting a real existing Java project, it's likely we don't want to remove any Java activities. Or even if that file has already been modified. Perhaps we should give it another name and modify the XML file so that it points to the new Ceylon version instead?

**Comment by bjansen** [comment]
No, we're not converting the project from Java to Ceylon, we're configuring it to add support for Ceylon declarations (add a few things in the gradle build file, rebuild to setup the local repository, create a new *hardcoded* Ceylon activity, and do a full model update). So I think the best approach is to give the activity another name and leave the Java file as is.

**Comment by bjansen** [comment]
It's like "Add Ceylon nature" + create a new Ceylon file, in Eclipse terms.

**Comment by bjansen** [comment]
We *could* convert the main activity from Java to Ceylon, but it's very likely that the converter will produce slightly invalid code that will break the build.

**Comment by FroMage** [comment]
Leave the Java file, sure. But what about updating the XML file to point to the new Ceylon activity?

**Comment by bjansen** [comment]
I can think of two use cases:

* the user creates a brand new project, clicks "add Ceylon support" and writes most of the app in Ceylon
* the user has an existing project, and wants to play with Ceylon, so he clicks "add Ceylon support" and adds Ceylon code on top of existing code

I think in the second case, the user will want to keep the XML file intact, because the *main* activity might still be the one written in Java, but it will call new code written in Ceylon.

So in some cases it might be okay to update the XML file, in other cases it might be unwanted. Maybe we can show a dialog to let the user decide if he wants to update the manifest?

**Comment by FroMage** [comment]
Fine by me, excellent.

**Comment by bjansen** [comment]
Actually, "replacing the main activity" might not be that straightforward, because if we simply replace a name with another in the `<activity>` tag that has the `android.intent.action.MAIN` intent, we may end up with a "corrupt" manifest (i.e. tags or attributes that don't make sense for the new activity). Perhaps we should let users adjust the manifest by themselves, that way we won't have to guess what the correct modifications are?

**Comment by FroMage** [comment]
OK, fair enough.

**Comment by bjansen** [comment]
To sum up:

* "Configure Ceylon in this module" will create a new Ceylon activity
* existing Java activities won't be modified/deleted
* it's up to the user to change the manifest to declare the Ceylon activity as the "main activity"

So, the only thing that I changed is the name of the Ceylon activity, to avoid a dupe with the Java class.

Is that correct?

**Comment by FroMage** [comment]
Yes.

**Comment by bjansen** [comment]
The activity is now named `CeylonMainActivity`, so I suppose it's enough for this issue.

**Comment by FroMage** [comment]
The file name should be `CeylonMainActivity.ceylon` then, to be consistent. And also that's an activity without layout. You need this file in `app/src/main/res/layout/activity_main_ceylon.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.android.myapplication.CeylonMainActivity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!" />
</RelativeLayout>
```

**Comment by bjansen** [comment]
Fixed.
