### ISSUE TITLE
Allow manual ceylon model update

### ISSUE THREAD

**Issue by karimiumar** [ceylon/ceylon-ide-intellij#448]
At the moment maximum time is taken up by the "ceylon model update" background processes and makes the IDE unusable. 
Is there a way to stop Ceylon Intellij IDE from automatically updating ceylon model. And rather let the user choose Make project or rebuild project?

**Comment by bjansen** [comment]
Unfortunately, disabling model updates will basically break Ceylon IDE. Changes made to a file won't be visible from other files; code completion, quick fixes, refactorings etc. will likely not work as expected.

Once the project has finished loading, model updates should not happen that often, most of the time is when you switch to another editor, modify a class/function signature, or basically any kind of change that could have impacts on other files. This model update should be rather quick (< 2s).

What kind of project do you have, does it contain a lot of source files? a lot of dependencies?

**Comment by karimiumar** [comment]
Well I'm experimenting with the JOOQ-Ceylon, the one provided by you along with sakiladb using postgresql. 

The model updates keep happening every time a new source file/package.ceylon is added.

Model updates can be disabled in Eclipse IDE too using "Do no automatically build" option and when one builds the project, it just works fine.

What I'm suggesting is to turn off the automatic model update and let the user add all the dependencies and package structures as required and let him choose whether to build the model automatically or manually.

Here's my module entry
shared import ceylon.interop.java "1.2.2";
    shared import java.jdbc "8";
    shared import ceylon.time "1.2.2";
    shared import java.base "8";
    shared import javax.jaxws "8";
    shared import javax.annotation "8";
    shared import "org.jooq:jooq" "3.8.4";
    shared import "org.jooq:jooq-codegen" "3.8.4";
    shared import "org.jooq:jooq-meta" "3.8.4";
    shared import "org.postgresql:postgresql" "9.4.1209";

**Comment by karimiumar** [comment]
Well I just found that Ceylon IntelliJ IDE automatically disables Ceylon Model Update with the following message "

> Ceylon Model Update failed
				The Ceylon model update triggered an unexpected exception: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/psi/impl/PsiDocumentManagerBase.getLastCommittedDocument must not be null that will be reported in the Event View.
				To avoid performance issues the automatic update of the Ceylon model has been disabled.
				You can reenable it by using the following menu entry: Tools -> Ceylon -> Enable auto

So that feature is already provided by the IDE. However, it still automatically updates without letting the user Re-enable this feature.  And it would be really nice if the default 4 seconds can be made configurable

**Comment by davidfestal** [comment]
This is already available in:
- `Tools -> Ceylon -> Disable/Enable automatic model update`
- `Tools -> Ceylon -> Reset Ceylon Model` to run the model update manually.

And in the Ceylon global settings, you can change the automatic model update period.

**Comment by davidfestal** [comment]
and could you report the error message you encountered in an issue, possibly with the stacktrace that might be available in your event log view or log file ?

**Comment by karimiumar** [comment]
Well I had to kill the IDE as it was unresponsive and I cannot find any exceptions in my logs that will be of value to you. Also, it created a huge 837 MB .hprof file.

**Comment by bjansen** [comment]
You might have to [give IntelliJ a bit more memory](https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties), because the default 500-750MB can cause a lot of GC, which makes the IDE unusable.

FTR, I use `-Xmx3G` to open both `ceylon-ide-intellij` and `ceylon-ide-common` and I have no problem (they pull big dependencies). For more reasonably sized project, I think 1G or 1.5G should be enough.

**Comment by gavinking** [comment]
So, TBH, I think that @karimiumar does have a point here. We've always been working from the assumption that when you update the model, you need to immediately re-typecheck everything that depends on the change.

And, indeed there's a *huge* advantage to doing that: we get to see errors that result from the change in the Ceylon Problems window, immediately, just like in Eclipse, and *unlike* in the Java editor for IntelliJ, which lets me make changes which break other code, without informing me of the breakage.

*However*, for sure there are IntelliJ users who are pretty happy with this (quite nasty, IMO) behavior of IntelliJ, and might be happy to trade it for a much faster model update.

So, what if we merely updated the model, and didn't eagerly typecheck dependent files?

> Changes made to a file won't be visible from other files; 

Well, that's not quite true. They will be, as soon as you open the other file, which is actually the behavior that IntelliJ users are accustomed to.

> code completion, 

Would work fine.

> quick fixes, 

There are *very* few quick fixes that impact other files, and for the ones which do, we could do something explicit.

> refactorings etc.

That's really not clear: Extract refactorings wouldn't be affected at all. And I suspect that it wouldn't even break Rename. As for Change Signature, I think you could easily enough delay the typechecking until someone actually *runs* a Change Signature refactoring.


So what I would propose is this:

Add an option to Ceylon IDE so that instead of actually *typechecking* files that depend on the updated model, simply mark them as "dirty". Then when something happens that really requires that they be typechecked, go ahead and do it, but do it lazily.

**Comment by davidfestal** [comment]
First, without changing the whole default model update lifecycle, what can be done very easily is adding a menu entry `Update Ceylon Model` with an associated shortcut (I found `ctrl + Alt + U` available under Linux / Gnome, don't know what the equivalent is under Mac). That would allow the user to:
- disable fully the automatic model update, which is already available now
- or increase the automatic model update to a higher period, 
- *but* still have the ability to manually start an incremental model update with an easily accessible shortcut.

Additionally, I'm currently testing the impact of reducing the priority of the model update thread during the CPU-consuming part of the model update.  

Those 2 enhancements might be enough to make the whole usable IMO.

And honestly I don't feel very comfortable with the idea of *lazily* performing the model update before refactorings or other synchronous UI actions. First this can take time if there are many transitive dependencies involved in dirty files, and secondly this means triggering the model update and *waiting for its the end" during the UI action, which would have very bad impacts in terms of UI and might even be dead-lock-prone.

IMO the right way to go is:
- reduce the priority of the model update thread so that it doesn't prevent editing,
- allow a way to disable automatic model update (already there) but also to trigger it manually (not there for now)
- reduce the average number of files involved in incremental model updates, by removing the requirement of typechecking transitive dependencies that are not changed themselves (which is already planned, but is not a `ceylon-ide-intellij`-specific task)

**Comment by davidfestal** [comment]
This would also be consistent with *power-save* mode: in power save mode we should at least disable the automatic model update and, why not, the local typechecking.

**Comment by gavinking** [comment]
@davidfestal well I think you're sliding over the whole point of what I propose above: I don't want to disable the model update. I want to delay the *typechecking* that happens *after* the central model has been updated. These are actually two distinct things, and the first thing is much faster than the second thing.

> And honestly I don't feel very comfortable with the idea of lazily performing the model update before refactorings or other synchronous UI actions. First this can take time if there are many transitive dependencies involved in dirty files, and secondly this means triggering the model update and *waiting for its the end" during the UI action, which would have very bad impacts in terms of UI and might even be dead-lock-prone.

I strongly disagree. I would *much* prefer that certain (not all!) refactorings are slower than that the UI sometimes locks up when I'm just trying to type stuff. From a user perspective I'm already expecting that a refactoring is a potentially slow operation, and it's one I only rarely invoke, and invoke explicitly. It's *far* more annoying when the UI pauses when I'm just trying to type stuff.

> reduce the priority of the model update thread so that it doesn't prevent editing

I agree that just this might almost completely solve the problem. We need to try that first.

> allow a way to disable automatic model update (already there) but also to trigger it manually (not there for now)

No, I don't think this is what I want as a user. I don't want to have to remember to explicitly trigger a model update in order to be able to have autocompletion work reliably in my project. I think this is the lame solution.

**Comment by bjansen** [comment]
> No, I don't think this is what I want as a user. I don't want to have to remember to explicitly trigger a model update in order to be able to have autocompletion work reliably in my project. I think this is the lame solution.

I agree with this.

**Comment by davidfestal** [comment]
> annoying when the UI pauses when I'm just trying to type stuff.

>> reduce the priority of the model update thread so that it doesn't prevent editing

> I agree that just this might almost completely solve the problem. We need to try that first.

That's the point n which we all agree, and that's what I've worked on with the previous commits.

- Analyzing the running application with Java Mission Control showed that the locks in the UI while a model update was running were not primarily due to CPU load, but to inter-dependencies between the background threads and UI when auto-completion was automatically triggered.
I fixed this, but still allowed  limited immediate completion during the model update (with a warning about incomplete result). 

- In case it is not sufficient and editing is still intermittent, I've added a setting to decrease the processing priority of model updates (without decreasing the priority of the involved read-access sections(which would also indirectly impact the UI thread).

- That should be sufficient for general editing, but, since module descriptor editing is not yet optimized and may fire many model updates, I added the general ability to trigger an incremental model update manually. This can also be useful when one want to see immediately if some change (in a method body for example) fixed errors in the problem list. I added it with the `Ctrl + Alt+ U` shortcut.
 
I'll answer your previous comments later, but IMO it seems to be really usable now, without needing to change the overall model update lifecycle (at least for the release 1.3.0).

**Comment by gavinking** [comment]
With David's the latest work, this is now a nonissue, since model updates don't get in the way of other work. It would still be nice to reduce the amount of typechecking work done during a model update (it still seems excessive to me, either the model diff process or the dependency tracking could do with some work) but that's really not such a big deal anymore now that all this work happens in the background.

**Comment by gavinking** [comment]
To be clear: David has actually implemented the requested functionality, though I doubt you'll need to use it.

<img width="842" alt="screen shot 2016-09-07 at 11 12 34 am" src="https://cloud.githubusercontent.com/assets/579974/18306425/1afa88e6-74ec-11e6-96b6-ae5ddb8c4093.png">

**Comment by karimiumar** [comment]
Excellent ! This is working as desired. :)

On 9/7/16, Gavin King <notifications@github.com> wrote:
> To be clear: David has actually implemented the requested functionality,
> though I doubt you'll need to use it.
>
> <img width="842" alt="screen shot 2016-09-07 at 11 12 34 am"
> src="https://cloud.githubusercontent.com/assets/579974/18306425/1afa88e6-74ec-11e6-96b6-ae5ddb8c4093.png">
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ceylon/ceylon-ide-intellij/issues/448#issuecomment-245222404


-- 
regards

Umar
