### ISSUE TITLE
trigger model update when Problems receives focus

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#510]
It would be nice if focussing the Problems window triggered a model update. It would also be cool if it had a Refresh button that did the same thing.

**Comment by bjansen** [comment]
Done, I also added a button to *reset* the model from the Problems view. I'm not sure the 'refresh' button is very useful, though, because as soon as you focus the Problems view to click it, the model is automatically updated.

<img width="425" alt="capture d ecran 2016-12-09 a 15 18 48" src="https://cloud.githubusercontent.com/assets/281528/21051948/d2695492-be22-11e6-9f72-199b66cd13d0.png">

**Comment by gavinking** [comment]
Great!! At last :)
