### ISSUE TITLE
impossible to run cross-platform project on node

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#525]
Right now if I enable both compiler backends, I can't run my program on JS, even if I manually create the run configuration.

**Comment by bjansen** [comment]
Reproducible by creating a JS run config manually, on the default module.

**Comment by bjansen** [comment]
I have a fix, but for existing projects, the "default" backend for JS configurations has already been set in `.idea/workspace.xml`, and there's not way to fix it from the UI:

```xml
    <configuration default="true" type="CeylonJsRunConfiguration" factoryName="Ceylon JavaScript" ceylon-module="" top-level="" backend="jvm" arguments="" vm-options="">
      <module name="" />
      <method />
    </configuration>
```

I'll have to make an ugly fix to the code to force the backend to "js" in existing projects.

**Comment by bjansen** [comment]
As discussed on Gitter, I've just merged the JS and JVM configuration types. Unfortunately, this means existing JS configurations will be lost.

* When you right-click on a runnable declaration, there is now a single 'Run' entry (instead of 'Run -> Java' and 'Run -> JVM').
* Configurations automatically created via right-clicking on a runnable will default to 'Java' if the module has no `native` annotation, otherwise it chooses a backend according to the annotation.
* There is a new combobox to change the backend on which to run the declaration.
* The list of possible backends depends on the selected module.

@gavinking I only pushed on master for now, could you test the fix when you have time before I cherry-pick it on the branch please?

**Comment by gavinking** [comment]
@bjansen it looks reasonable to me.

However, a comment: it seems to me that it was a mistake to remove the little gutter icon on runnable functions and classes. I think we should put it back.

**Comment by bjansen** [comment]
Done.

**Comment by gavinking** [comment]
Thanks.
