### ISSUE TITLE
bug with collect() and SAM conversions 

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#532]
See ceylon/ceylon/issues/6580, which turns out to be a bug in the IntelliJ model loader.

**Comment by FroMage** [comment]
You're probably not applying the type arguments properly.

**Comment by bjansen** [comment]
I don't even know where `U` comes from :s

**Comment by FroMage** [comment]
From https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html

**Comment by FroMage** [comment]
Sorry https://docs.oracle.com/javase/8/docs/api/java/util/function/BiConsumer.html as used in https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#collect-java.util.function.Supplier-java.util.function.BiConsumer-java.util.function.BiConsumer-

It's really that you didn't apply the argument types right.

**Comment by bjansen** [comment]
Yes, I just figured that... IntelliJ tells me the return type is `R`, but in fact it's `T` from the PoV of `BinaryOperator`.

**Comment by gavinking** [comment]
Thanks @bjansen, very fast.

**Comment by bjansen** [comment]
Not entirely fixed, apparently:

```ceylon
value list = Arrays.asList("foo", "bar", "baz", "bam", "crash");

print(list.stream().allMatch((str) => str.longerThan(2)));
```

**Comment by bjansen** [comment]
In `Stream` we have this method:

```java
boolean allMatch(Predicate<? super T> predicate);
```

with

```java
@FunctionalInterface
public interface Predicate<T> {
    boolean test(T t);
}
```

What's happening is that when I use IntelliJ's API to retrieve the parameter types for the SAM, it finds a type `? super T`, which is of kind `TypeKind.WILDCARD` and has a lower bound of type `T`. The model loader then calls `convertNonPrimitiveTypeToDeclaration` and falls into this case:

```java
        case WILDCARD:
            return typeFactory.getNothingDeclaration();
```

That's why we end up with `Boolean(Nothing)`. 

When I debug the CLI compilation, I can see that `CeylonModelLoader` generates a parameter type of kind `TypeKind.TYPEVAR` for `T`. It seems that it's completely skipping the bounded wildcard type `? super T`, which seems a bit odd.

I could do the same in `getFunctionalInterfaceType` and return `wildcardType.bound` instead of `wildcardType`, but that doesn't seem right. WDYT @FroMage ?

**Comment by FroMage** [comment]
Wildcards are usually dealt with in `applyTypeArguments`, which is why we don't get at the `case` you mention.

**Comment by FroMage** [comment]
But otherwise yeah, just try to do the same as what `javac` does for us?
