### ISSUE TITLE
Spurious errors with modules under test sources root

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon-ide-intellij#592]
1. In a Ceylon project, create a `test-source` directory
2. Mark it `Test Sources Root`
3. Create a module under it
4. You start to get errors about having code directly under the root directory.

**Comment by bjansen** [comment]
That's because marking the directory as `Test Sources Root` does not automatically add it as a source root in `.ceylon/config`, which means the plugin won't treat that directory as a source root. I'll modify the module wizard to do that configuration automatically: if you're creating a Ceylon module in a source root, it probably means that the typechecker should also see that folder as a source root :)

**Comment by bjansen** [comment]
Fixed!
