### ISSUE TITLE
Provide binaries for testing

### ISSUE THREAD

**Issue by Arcnor** [ceylon/ceylon-ide-intellij#60]
According to the README, a separate repo will be created to hold testing binaries.

I'm not sure if I misunderstood something, but you can do that right now on this very repository (on the "Releases" section) instead of having to create that separately.

**Comment by bjansen** [comment]
The thing is, if you want to be able to update the plugin automatically, we need to update an [XML file](http://downloads.ceylon-lang.org/ide/intellij/development/updatePlugins.xml
) that points to the current updated zip files. I guess we could create a "fake release" on Github that contains this XML file, and each time we publish a new release, updating this file/release would cause IntelliJ to download the new release...

I'm not sure it has a real added value compared to hosting the releases on ceylon-lang.org

Eventually, when we finally get a stable version, I think it would be nice to host the releases on plugins.jetbrains.com, so that we wouldn't even need to configure a special plugin repository in IntelliJ.

**Comment by bjansen** [comment]
To keep things easy and similar to the eclipse plugin, we'll continue to host binaries on ceylon-lang.org. When the plugin is stable enough, we'll eventually switch to the official Jetbrains repo.
