### ISSUE TITLE
completion autopopup seems to be broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#613]
Using a build of the IntelliJ plugin from master and IntelliJ 2016.3.4, autopopup of completion proposals no longer seems to work. I'm not sure at what point this broke.

**Comment by bjansen** [comment]
What's happening is that an optimization we added to compute proposals faster is half-broken: when we add more characters to an existing identifier, we skip the typecheck part because we know it shouldn't affect the result. But, this results in a `Node` that has a no scope (yet), and the completion manager needs that scope to compute proposals:

```ceylon
        value fsv = FindScopeVisitor(node);
        fsv.visit(typecheckedRootNode);
        value scope = fsv.scope;

        if (!exists scope) {
            return;
        }
```

**Comment by bjansen** [comment]
I got it working by finding the equivalent `Node` in the last typecheck compilation unit.
