### ISSUE TITLE
No SDK for new project

### ISSUE THREAD

**Issue by russel** [ceylon/ceylon-ide-intellij#65]
I created a new Ceylon project on a directory with existing sources. The project seems fine, I can edit files and the Ceylon logo appears associated with the file icon the project window. However there is no SDK associated with project. I added my JDK8, but the ceylon jar is not in the classpath. I guess I have to go hunting for the ceylon jar that comes with teh runtime plugin and associate that with the project.

Should this have happened automatically, rather than me having to do things manually?

**Comment by bjansen** [comment]
Quick preamble: this plugin is not ready for daily usage at the moment, and if you installed it from the repository, it's an old version.

That being said, a Ceylon projet should be based on a Java 7+ SDK. You do not need to configure extra libraries to point to a Ceylon installation. Internally, the plugin uses JAR files that are bundled in the `CeylonRuntime` plugin, but that's not visible in the project settings.

If you built and installed the current master, things have changed a little bit. Instead of a dedicated SDK, I recently introduced a Ceylon facet, that can be added to any Java based project. So in your case, since the project was imported from existing sources and a JDK was configured, I guess adding the facet should be enough to mark the project as "Ceylon enabled".

Did you have any error when you finished importing your project?

Also keep in mind that if your project is more complex than a "hello world file" (i.e. if you added dependencies in `module.ceylon` or created files with references to types declared in other files), chances are that you will get compilation errors. Hopefully this will be fixed in the near future, when we abstract and reuse parts of the Eclipse plugin.

**Comment by russel** [comment]
I am a bleeding edge kind of person, Fedora Rawhide, Debian Sid, Java 9,…

I did install from the repository, I was trying to avoid compiling from source, but if that is the best way then that is what I will do. Java 7 is dead, at least as of 2015-04. I do not have any Java 7 installations, maybe that is what caused the problem? 

Using a Ceylon facet on a JDK8 SDK would work for me. I was trying to construct a Ceylon Global Library by pointing at the Ceylon Runtime plugin library.

My project is relatively trivial but it is more complex that Hello World, it is my "π by quadrature" codes.

**Comment by bjansen** [comment]
By "Java 7+" I meant, 7, 8 or possibly 9 :)

If you decide to go the facet way, then you need to build the plugin from sources. Once it's done, there is a trick to import the project, because right now the plugin does not detect Ceylon sources in the "Import project" wizard. So, you need to *create* a Java project from scratch (not import existing sources), with the path set to `.../Pi_Quadrature/Ceylon/`. This will create a Java based project (otherwise, in my tests, I ended up with a Web-based project), and the facet detector will ask if you would like to configure a Ceylon facet. You can leave the settings empty, they are not used (yet) anyway :). 

Once the facet is configured, you just have to mark the `source` directory as "sources root". You will likely have red/underlined code here and there because imports are broken at the moment, but compiling and running top-level functions should work since it relies on the actual Ceylon compiler/runner.

**Comment by bjansen** [comment]
I published a new dev build a few days ago, with the following features that you've been waiting for:

* Ceylon facet
* Import from existing sources

You might want to update IntelliJ and try it.
